### ISSUE TITLE
Allready working?

### ISSUE THREAD

**Issue by timoline** [jordenc/tv.horizon.ziggo#1]
I changed the function Hex2Bin to:

function Hex2Bin (s) {
	return new Buffer(s,"hex");
}

now its working for me

ps I'm not using athom, I changed your code to my needs ;-)

**Comment by jordenc** [comment]
Thanks for your comment. That might be the thing I did wrong, let me check this weekend. If it works for you it probably should work for everyone, which means you might have made a lot of people very happy!

**Comment by jordenc** [comment]
Awesome, it works!
