### ISSUE TITLE
how to set ip

### ISSUE THREAD

**Issue by nattlip** [jordenc/tv.horizon.ziggo#2]
how to set ip of my horizon box ? i get invalid ip and cant set it in the device, nor can i set it inthe code, howecto change it in the code so i can install it with cli ? i get error valid ip address must be set .

**Comment by nattlip** [comment]
i found it set cursor at begin of ip , i was misguided by presshonw ip, nothing happens though isn flow, i use the ip where i can login yiggo it is a client in my netzwork not the router

**Comment by jordenc** [comment]
Yeah you need to fill in the correct IP. Does it work for you now?

**Comment by nattlip** [comment]
no sorry, i use the ip where i can log in in my horizon box,nothing happens when i use a flow on /off etc  my horizonbox is a client in my network not the router. maaybe that is the issue ?

**Comment by jordenc** [comment]
Can you try to add the "next" IP? If you now use 192.168.1.1, try 192.168.1.2

Perhaps that works

**Comment by nattlip** [comment]
ithank you for the tip , ill try when i am home again after the weekend


________________________________
Van: Jorden <notifications@github.com>
Verzonden: zaterdag 29 juli 2017 10:31:18
Aan: jordenc/tv.horizon.ziggo
CC: nattlip; Author
Onderwerp: Re: [jordenc/tv.horizon.ziggo] how to set ip (#2)


Can you try to add the "next" IP? If you now use 192.168.1.1, try 192.168.1.2

Perhaps that works

**Comment by nattlip** [comment]
yes your tips works @jordenc  , i think you should mention this in the readme
